### PR TITLE
Updated to our League of Linux Community wine build and added back Ap…

### PR DESCRIPTION
**Pull request by polkaulfield**
…pImage CI.

### CODE REVIEW

**Comment by kassindornelles** [comment]
oh god i was in a hurry and didnt see your PR, i already did it myself hahaha

good work everyone, the league on linux community is fantastic!

**Comment by polkaulfield** [comment]
I fixed the riotclientservices hanging at the end and exiting the installer after finishing the installation too, check my last 2 commits

**Comment by kassindornelles** [comment]
i'm gonna be reviewing the new PR's later today or tomorrow

**Comment by polkaulfield** [comment]
No problem! Doing the same work kinda messed it up hahah. You can check the changes and cherrypick if you want, I'll fetch your changes.

**Comment by polkaulfield** [comment]
Do you mind if I'm releasing the AppImages? I kept all your donations and stuff in the readme, didnt change anything

**Comment by kassindornelles** [comment]
> Do you mind if I'm releasing the AppImages? I kept all your donations and stuff in the readme, didnt change anything

yup, do it

**Review by kassindornelles — APPROVED** [review]

**Comment by kassindornelles** [comment]
i cherry-picked the client hang one and its already in main!

would be cool for you to commit the appimage stuff to the 'automated poors-man-edition build system' i have in:
https://github.com/kassindornelles/lol-for-linux-installer-packages

**Comment by kassindornelles** [comment]
Feel free to ask questions or anything even if this PR is closed

**Comment by polkaulfield** [comment]
Will

> i cherry-picked the client hang one and its already in main!
> 
> would be cool for you to commit the appimage stuff to the 'automated poors-man-edition build system' i have in: https://github.com/kassindornelles/lol-for-linux-installer-packages

Will do!

**Comment by polkaulfield** [comment]
https://github.com/polkaulfield/lol-for-linux-installer/releases/tag/v2.6.5

I updated it to you latest commits

**Comment by kassindornelles** [comment]
@polkaulfield i made a new release, i can point to your appimage if you make a new one, also, can you ship 32 bit libraries with your appimage? ubuntu dropped a lot of 32 bit libs necessary by WINE to run league

**Pull request closed without merging**
