### PR TITLE
lol-for-linux flatpak(or at least it's draft)

### PR DESCRIPTION
**Pull request by Vilianexe**
installation of lol-for-linux' module is finished(i guess?), missing Lutris-GE-lol module and its dependencies

### CODE REVIEW

**Comment by kassindornelles** [comment]
also, i think would be much better a completely separate repository just for the flatpak stuff, so when is done we advertise  it in the readme of this project (and hopefully get it on flathub if it works well)

**Comment by Vilianexe** [comment]
> is this usable rn?

nop , it only install the lol-for-linux-installer, not the wine or it dependencies

**Comment by Vilianexe** [comment]
ok, err, just tobe sure the main binary is `lol-for-linux-installer.py` correctly?

**Comment by Vilianexe** [comment]
nevermind, I discovered the problem
image

python dependencies

**Comment by Vilianexe** [comment]
https://docs.flatpak.org/en/latest/python.html
if i'm understanding the problem correctly, i think we gonna need to use [flatpak-pip-generator](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip)

**Comment by kassindornelles** [comment]
theres no runtime for python in flatpak? python3-utils is the package

**Comment by Vilianexe** [comment]
btw the installer uses Qt5 or qt6?

**Comment by kassindornelles** [comment]
> btw the installer uses Qt5 or qt6?

qt5 (pyqt5)

**Comment by kassindornelles** [comment]
> ok, err, just tobe sure the main binary is `lol-for-linux-installer.py` correctly?

yes, thats the one we use to launch the app, if the game is installed it will open the launcher, if is not installed it opens the installer

**Comment by kassindornelles** [comment]
theres a few hardcoded paths in the `lol-for-linux-installer.py` file tho

not sure if you will need to change them for the flatpaked version

**Comment by Vilianexe** [comment]
```
module_folder = "/usr/share/lol-for-linux-installer"
sys.path.append(module_folder)
```
yeah, i can totally see this giving problems, but i'm still trying to resolve the dependencies, when i finally build the flatpak we can confirm if it work or not

**Comment by kassindornelles** [comment]
> ```
> module_folder = "/usr/share/lol-for-linux-installer"
> sys.path.append(module_folder)
> ```
> 
> yeah, i can totally see this giving problems, but i'm still trying to resolve the dependencies, when i finally build the flatpak we can confirm if it work or not

i removed the module_folder and sys.path.append code and is running fine, so in the end is not really necessary, we dont use it anywhere else either

**Comment by Vilianexe** [comment]
ok, now i don't have any idea why the python isn't detecting psutil, i installed with the flatpak-pip and isn't different from other projects [glases](https://github.com/nicolargo/glancesflatpak), maybe i installed the wrong module?, or , because i changed the default local of the lol-for-linux-installer?

it was installed in /usr/bin correctly? and i changed it to /app/bin, but pip is installing in the default /usr/bin, i guess, i don't know how to use pip lol

**Comment by Vilianexe** [comment]
ok, i can't install in /usr/bin/lol-for-linux-installer, maybe se i changed the pip default path, how i could do this

**Comment by Vilianexe** [comment]
or not idk 😅

**Comment by Vilianexe** [comment]
other projects put everything in pip and just install with flatpak-pip [like here](https://github.com/nicolargo/glancesflatpak/blob/main/com.github.nicolargo.Glances.yml)as you can see,only 1 module, and when you go to that module, is everything, even the main binary, they let flatpak-pip handle everything, and idk how or where pip or flatpak-pip install it, urg, or i could be very wrong too

**Comment by Vilianexe** [comment]
other projects put everything in pip and just install with flatpak-pip [like here](https://github.com/nicolargo/glancesflatpak/blob/main/com.github.nicolargo.Glances.yml)as you can see,only 1 module, and when you go to that module, is everything, even the main binary, they let flatpak-pip handle everything, and idk how or where pip or flatpak-pip install it, urg, or i could be wrong too

**Comment by kassindornelles** [comment]
> ok, i can't install in /usr/bin/lol-for-linux-installer, maybe se i changed the pip default path, how i could do this

you can check what is the expected behavior for it to work by looking at the PKGBUILD content
https://github.com/kassindornelles/lol-for-linux-installer-pkgbuild/blob/main/archlinux/PKGBUILD

**Comment by kassindornelles** [comment]
> ```
> module_folder = "/usr/share/lol-for-linux-installer"
> sys.path.append(module_folder)
> ```
> 
> yeah, i can totally see this giving problems, but i'm still trying to resolve the dependencies, when i finally build the flatpak we can confirm if it work or not

i was wrong, we actually need this to exist

[kassin@kassin-pc arch-linux-git]$ lol-for-linux-installer
Traceback (most recent call last):
  File "/usr/bin/lol-for-linux-installer", line 8, in <module>
    import leagueinstaller_code
ModuleNotFoundError: No module named 'leagueinstaller_code'

**Comment by kassindornelles** [comment]
the thing is about finding out where all the files are going in the flatpak and making a exception for it

**Comment by kassindornelles** [comment]
> other projects put everything in pip and just install with flatpak-pip [like here](https://github.com/nicolargo/glancesflatpak/blob/main/com.github.nicolargo.Glances.yml)as you can see,only 1 module, and when you go to that module, is everything, even the main binary, they let flatpak-pip handle everything, and idk how or where pip or flatpak-pip install it, urg, or i could be wrong too

so basically we need to package it as pip first?

**Comment by Vilianexe** [comment]
> > other projects put everything in pip and just install with flatpak-pip [like here](https://github.com/nicolargo/glancesflatpak/blob/main/com.github.nicolargo.Glances.yml)as you can see,only 1 module, and when you go to that module, is everything, even the main binary, they let flatpak-pip handle everything, and idk how or where pip or flatpak-pip install it, urg, or i could be wrong too
> 
> so basically we need to package it as pip first?

it's gonna be easier this way

**Comment by Vilianexe** [comment]
> i was wrong, we actually need this to exist
> 
> [kassin@kassin-pc arch-linux-git]$ lol-for-linux-installer Traceback (most recent call last): File "/usr/bin/lol-for-linux-installer", line 8, in import leagueinstaller_code ModuleNotFoundError: No module named 'leagueinstaller_code'

instead of /usr/bin, there aren't some way to but like, /$ROOT/usr/bin?, so it's gonna work in every case?

**Comment by kassindornelles** [comment]
for now you can modify the path on your branch to whatever it needs to be, then we figure this later

**Comment by Vilianexe** [comment]
finally resolved the dependencies, but

**Comment by Vilianexe** [comment]
ok, this is new
image

**Comment by Vilianexe** [comment]
> i was wrong, we actually need this to exist
> 
> [kassin@kassin-pc arch-linux-git]$ lol-for-linux-installer Traceback (most recent call last): File "/usr/bin/lol-for-linux-installer", line 8, in import leagueinstaller_code ModuleNotFoundError: No module named 'leagueinstaller_code'

oh, it's exactly the same problem

**Comment by Vilianexe** [comment]
image
image

what about just detecting if the container variable is set and changing the path of the modules?

**Comment by Vilianexe** [comment]
image
 i resolved the first import path in the commit ahead, with a simple if else, now idk how to fix here

**Comment by kassindornelles** [comment]
> image i resolved the first import path in the commit ahead, with a simple if else, now idk how to fix here

where is the installer.ui located when flatpaked?
you can point to that inside the "try:"

**Comment by kassindornelles** [comment]
You can apply the same logic as this:
but for the .ui file where we load it

```
if 'cointainer' in os.environ:
    module_folder = "/app/usr/share/lol-for-linux-installer"
    sys.path.append(module_folder)
else:
    module_folder = "/usr/share/lol-for-linux-installer"
    sys.path.append(module_folder)```

**Comment by Vilianexe** [comment]
> where is the installer.ui located when flatpaked? you can point to that inside the "try:"

same path, just with an app/ before the usr/

**Comment by Vilianexe** [comment]
image

what i did wrong :/

**Comment by kassindornelles** [comment]
It's just not finding the .ui file

**Comment by Vilianexe** [comment]
> It's just not finding the .ui file

why?

**Comment by Vilianexe** [comment]
bro it's fine, rest as much as you need, food poison ain't a joke

**Comment by Vilianexe** [comment]
i really don't know why it isn't finding the installer.ui

**Comment by kassindornelles** [comment]
any progress?

**Comment by kassindornelles** [comment]
> image
> 
> what i did wrong :/

can you try to load the ui file directly inside the Try: first to see if it works?

**Comment by Vilianexe** [comment]
image
ok, this worked, now i'm gonna try to see a way to work in flatpak and outside it

**Comment by Vilianexe** [comment]
image
here what i did, it's working in the flatpak i can't test in the normal installation, i'm gonna try to play the game, to see if it has other problems

**Comment by Vilianexe** [comment]
image
:/

btw, if running inside the flatpak, i don't think it's necessary to ask the user where to install the game, actually i think it's better to just default to inside the flatpak, so  when the flatpak get removed, it also remove the game

**Comment by Vilianexe** [comment]
```
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
INFO: Setting all variables

INFO: Creating folders

INFO: Downloading WINE build

INFO: Downloading League of Legends installer from https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.br.exe

INFO: All files Downloaded

INFO: Extracting the WINE build file

INFO: Extraction of the WINE build file completed

Traceback (most recent call last):
  File "/app/bin/lol-for-linux-installer", line 604, in run
    leagueinstaller_code.league_install_code(self.game_main_dir, self.game_region_link)
  File "/app/usr/share/lol-for-linux-installer/leagueinstaller_code.py", line 83, in league_install_code
    subprocess.run(["wine", league_installer_file], env=first_boot_envs, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
```
hmmm, this don't look good

**Comment by kassindornelles** [comment]
Seems like it's failing to create folders and move files

**Comment by Vilianexe** [comment]
> Seems like it's failing to create folders and move files

hmm, i guess, can you disable to where save the game files when installing from flatpak, so everything is inside the flatpak, that could resolve the issue, and be easier to uninstall the game, just uninstall the flatpak and every file is unstalled too

**Comment by kassindornelles** [comment]
> > Seems like it's failing to create folders and move files
> 
> hmm, i guess, can you disable to where save the game files when installing from flatpak, so everything is inside the flatpak, that could resolve the issue, and be easier to uninstall the game, just uninstall the flatpak and every file is unstalled too

you can toy around and do flatpak specific paths for now, then later i check and try to fit it all in upstream code

**Comment by Vilianexe** [comment]
`basically get it working first and then we figure it out!`

the app is opening and such, but it ask to choose where to install, and even when i try to disable it, others problems surges uhh, i don't understand python enough, can you added an exception for the flatpak, that when container is detected it install the wine in /app/{where you prefer, like bin}, i can make it work that way, at least i know where the game is installed

**Comment by kassindornelles** [comment]
i never really messed much with flatpak, how can i build the flatpak with your branch?

**Comment by Vilianexe** [comment]
> i never really messed much with flatpak, how can i build the flatpak with your branch?

basicly go here 'https://github.com/Vilianexe/flathub/tree/com.kassindornelles.lol-for-linux-installer' copy the .yaml file, or clone de repo

Download the flatpak-builder from your distro repo, or download the flatpak version of the flatpak builder(if you install the flatpak version you need to put 'flatpak run' before every command and change flatpak-builder to org.flatpak.Builder'

go to the folder that you put your .yaml file and run `flatpak-builder --user --force-clean --install flatpak-folder com.kassindornelles.lol-for-linux-installer.yaml`
this is gonna build the faltpak in a folder named flatpak-folder and the --install gonna install automatically in your pc

to run the program in the terminal for the logs `flatpak run com.kassindornelles.lol-for-linux-installer`

**Comment by Vilianexe** [comment]
and there is a bug, tho, when you click to install league of legends, the program tries to open the portal, but i guess i disabled it somewhere, so it freeze, but i can stop the portal process in the task manager, so the program just crash because of not selected path

**Comment by kassindornelles** [comment]
> and there is a bug, tho, when you click to install league of legends, the program tries to open the portal, but i guess i disabled it somewhere, so it freeze, but i can stop the portal process in the task manager, so the program just crash because of not selected path

Can you rebase it to the latest release? (If isn't already done)
Then tomorrow I'm gonna work on it and help figure out why things are breaking

Thanks for your effort!

**Comment by kassindornelles** [comment]
hmm, i cant build it

**Comment by Vilianexe** [comment]
> Can you rebase it to the latest release? (If isn't already done) Then tomorrow I'm gonna work on it and help figure out why things are breaking

updated!

> hmm, i cant build it
what error it shows?

**Comment by kassindornelles** [comment]
> > Can you rebase it to the latest release? (If isn't already done) Then tomorrow I'm gonna work on it and help figure out why things are breaking
> 
> updated!
> 
> > hmm, i cant build it
> 
> what error it shows?

```removed '/app/share/locale/vi'
rmdir: removing directory, '/app/share/runtime/locale'
rmdir: removing directory, '/app/share/runtime'
rmdir: removing directory, '/app/share/locale'
rmdir: removing directory, '/app/translations'
removed '/app/cleanup-BaseApp.sh'
Committing stage cleanup to cache
Error: fstatat(.fuse_hidden0000000800000002): Arquivo ou diretório inexistente
```

**Comment by kassindornelles** [comment]
nvm i think i fixed it by doing `flatpak install flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08`

**Comment by kassindornelles** [comment]
i see errors about paths, but i dont know where things are installed

**Comment by kassindornelles** [comment]
oh i see `/home/kassin/.local/share/flatpak/app/com.kassindornelles.lol-for-linux-installer/x86_64/master/active/files/usr/share/lol-for-linux-installer/`

**Comment by kassindornelles** [comment]
ok, i think i can solve the problem with the installation, will be a long day but i think  i can make it work!

**Comment by Vilianexe** [comment]
what helped me was to look at others .yaml files in the flathub, just enter the flathub.org and in any app there is the manifest down there, there is the documentation of the flatpak too, i can help where i can, just ask, i couldn't make it work because i don't know python :/

**Comment by kassindornelles** [comment]
> what helped me was to look at others .yaml files in the flathub, just enter the flathub.org and in any app there is the manifest down there, there is the documentation of the flatpak too, i can help where i can, just ask, i couldn't make it work because i don't know python :/

you did a fantastic job, the hardest part basically, now i just have to deal with the container stuff and it looks pretty simple too based on the container cases you already dealt with

basically what i'm gonna do is: if running in container dont allow the user to select where to install the game, lets just create a folder in the var folder and call it a day

**Comment by kassindornelles** [comment]
ok nvm i removed the package to rebuild and got this shit again

```removed '/app/cleanup-BaseApp.sh'
Committing stage cleanup to cache
Error: fstatat(.fuse_hidden0000000800000002): Arquivo ou diretório inexistente
```

**Comment by Vilianexe** [comment]
> Error: fstatat(.fuse_hidden0000000800000002): Arquivo ou diretório inexistente
wait, do you speak Portuguese?

**Comment by kassindornelles** [comment]
> 


> > Error: fstatat(.fuse_hidden0000000800000002): Arquivo ou diretório inexistente
> 
> wait, do you speak Portuguese?
> 
> > we are hitting this problem with flatpak-builder, anything you can do on your end? [flatpak/flatpak-builder#319](https://github.com/flatpak/flatpak-builder/issues/319)
> 
> i never saw that bug, what changes you did?, i can try to build here áand see if the bug if from your end or in the flatpak itself

I'm brazilian

And about the bug it sometimes works, so is a race condition.

**Comment by Vilianexe** [comment]
po mano, se podia ter falado antes kkkkkkkkk

**Comment by Vilianexe** [comment]
> And about the bug it sometimes works, so is a race condition.

se vc tentar o flatpak-builder versão de flatpak isso acontece?, pois parece que era um bug em como o builder é compilado para arch-linux

**Comment by kassindornelles** [comment]
> 



> > And about the bug it sometimes works, so is a race condition.
> 
> se vc tentar o flatpak-builder versão de flatpak isso acontece?, pois parece que era um bug em como o builder é compilado para arch-linux

como q instala a versão do flatpak-builder em flatpak?

**Comment by Vilianexe** [comment]
`flatpak install org.flatpak.Builder`
é o mesmo comando explicado nas [docs](https://docs.flatpak.org/en/latest/first-build.html) do flatpak

**Comment by Vilianexe** [comment]
ai é como eu falei, vc tem que rodar `flatpak run org.flatpak.Builder` ao invés de só flatpak-builder(mas se pode fazer como eu e fazer uma alias para ser mais rápido)

**Comment by kassindornelles** [comment]
como q é o comando inteiro?

**Comment by kassindornelles** [comment]
ah deixa eu achei

**Comment by kassindornelles** [comment]
não sei o que ta rolando, mas na parte do codigo do instalador que extrai os arquivos da build do wine simplesmente não funciona no flatpak

**Comment by kassindornelles** [comment]
Algumas mudanças pra conseguir fazer flatpak, não afeta o codigo que roda fora de um container, mas eu simplesmente não consigo fazer a porcaria do arquivo tar extrair completamente por algum motivo
https://github.com/kassindornelles/lol-for-linux-installer/commit/3400fdbf8999fb8278741ded5c9397cdacec869b

**Comment by Vilianexe** [comment]
> Algumas mudanças pra conseguir fazer flatpak, não afeta o codigo que roda fora de um container, mas eu simplesmente não consigo fazer a porcaria do arquivo tar extrair completamente por algum motivo

se se a gente já instalar esse arquivo tar pelo .yaml do flatpak?, ai o flatpak-build já extrai e instalar ele onde é necessário.
Aliás onde vc está querendo que seja extraido esse tar?



meu merge request esta com conflitos, eu descarto eles?

**Comment by kassindornelles** [comment]
> > Algumas mudanças pra conseguir fazer flatpak, não afeta o codigo que roda fora de um container, mas eu simplesmente não consigo fazer a porcaria do arquivo tar extrair completamente por algum motivo
> 
> se se a gente já instalar esse arquivo tar pelo .yaml do flatpak?, ai o flatpak-build já extrai e instalar ele onde é necessário. Aliás onde vc está querendo que seja extraido esse tar?

league-of-legends/wine/wine-build/ que é o caminho comum no momento

> 
> meu merge request esta com conflitos, eu descarto eles?

acho que é melhor descartar, ja que eu vou tentar fazer as parada no codigo eu mesmo, mas se tu precisar contributir codigo também é só abrir outra pull request

**Comment by Vilianexe** [comment]
> league-of-legends/wine/wine-build/ que é o caminho comum no momento

quer que eu edit o .yaml para extrair aqui?, só preciso do link

**Comment by kassindornelles** [comment]
> > league-of-legends/wine/wine-build/ que é o caminho comum no momento
> 
> quer que eu edit o .yaml para extrair aqui?, só preciso do link

tu consegue extrair e renomear a pasta pelo yaml? pq ela precisa ter um nome especifico 
<https://github.com/kassindornelles/lol-for-linux-installer-wine-builds/releases/tag/8.7-4>

tipo assim:
https://github.com/kassindornelles/lol-for-linux-installer/blob/d9593348e0d94de96d5992dce7415eb5d87fd858/src/leagueinstaller_code.py#L76

**Comment by Vilianexe** [comment]
> tu consegue extrair e renomear a pasta pelo yaml? pq ela precisa ter um nome especifico https://github.com/kassindornelles/lol-for-linux-installer-wine-builds/releases/tag/8.7-4
> 
> tipo assim: https://github.com/kassindornelles/lol-for-linux-installer/blob/d9593348e0d94de96d5992dce7415eb5d87fd858/src/leagueinstaller_code.py#L79C1-L80C119

sim, calma ai, eu posso usar o wine-ge-lol "official" se vc quiser

**Comment by Vilianexe** [comment]
> > > league-of-legends/wine/wine-build/ que é o caminho comum no momento
> > 
> > 
> > quer que eu edit o .yaml para extrair aqui?, só preciso do link
> 
> tu consegue extrair e renomear a pasta pelo yaml? pq ela precisa ter um nome especifico https://github.com/kassindornelles/lol-for-linux-installer-wine-builds/releases/tag/8.7-4
> 
> tipo assim: https://github.com/kassindornelles/lol-for-linux-installer/blob/d9593348e0d94de96d5992dce7415eb5d87fd858/src/leagueinstaller_code.py#L79C1-L80C119

eu vou fazer assim extrair o tar, e mover tudo que estiver dentro da pasta lutris para /app/league-of-legends/wine/wine-build/
é isso que vc quis dizer?

**Comment by Vilianexe** [comment]
image
ficou assim

**Comment by kassindornelles** [comment]
> > tu consegue extrair e renomear a pasta pelo yaml? pq ela precisa ter um nome especifico https://github.com/kassindornelles/lol-for-linux-installer-wine-builds/releases/tag/8.7-4
> > tipo assim: https://github.com/kassindornelles/lol-for-linux-installer/blob/d9593348e0d94de96d5992dce7415eb5d87fd858/src/leagueinstaller_code.py#L79C1-L80C119
> 
> sim, calma ai, eu posso usar o wine-ge-lol "official" se vc quiser

contanto que seja a mesma build exata pois ela é tem patches especificos pro lol tudo bem

**Comment by kassindornelles** [comment]
> image ficou assim

exatamente assim, certinho

**Comment by Vilianexe** [comment]
que,, pq isso fechou

**Comment by Vilianexe** [comment]
abra

**Comment by Vilianexe** [comment]
ata, pq eu discartei os commits, deixa assim msm?

**Comment by Vilianexe** [comment]
mudei o link do yaml para puxar as mudanças desse repo seu, já que antes estava apontando pro meu fork

**Comment by Vilianexe** [comment]
acho que o flatpak está colocando o icone no lugar errado, onde seu programa procura pelos icones para atribuir ao launcher?
image
pq atualmente está assim

**Comment by kassindornelles** [comment]
> acho que o flatpak está colocando o icone no lugar errado, onde seu programa procura pelos icones para atribuir ao launcher? image pq atualmente está assim

Normalmente ele usa o ícone atrelado no arquivo .desktop mas nunca funcionou no Wayland, só no xorg

**Comment by Vilianexe** [comment]
image
eu fiz isso e funcionou, como assim, alías o programa está com o nome python3, será que é por isso?

**Comment by Vilianexe** [comment]
isso tbm acontece 
image
antes do fix
image
depois

parece que ele está atribuindo o .desktop errado, por isso não mostra um icone

**Comment by Vilianexe** [comment]
https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/
será que isso tem algo aver?

**Comment by kassindornelles** [comment]
arrumei o icone no wayland

image

**Comment by Vilianexe** [comment]
nice!

**Comment by Vilianexe** [comment]
droga, não consigo fazer funcionar

**Comment by Vilianexe** [comment]
no faltpak eu tenho que exportar os icones e o .desktop com o nome que parece uma url só que ao contrário(com.kassindornelles.lol-for-linux-installer), nisso eu tenho que renomear o ícone, ai seu programa não o coloca na gui :/, até tentei nesse ultimo pull request mudar o nome em todo o código, mas não adiantou

**Comment by Vilianexe** [comment]
talvez seja por causa que mudei no .destop `Icon=/usr/share/lol-for-linux-installer/lol-for-linux-installer.png` para apenas `com.kassindornelles.lol-for-linux-installer`?
vc tinha falado que seu programa buscava os ícones pelo .desktop talvez seja isso

**Comment by Vilianexe** [comment]
arrumei o icone para svg, mas aquele problema do icone no wayland continua

**Comment by Vilianexe** [comment]
o código já está instalando o jogo no flatpak?

**Comment by kassindornelles** [comment]
e aquela questão da build do wine lá que precisa ser extraida, ta tudo certo?

**Comment by Vilianexe** [comment]
ss, tá extraindo onde mostrei pra vc

**Comment by kassindornelles** [comment]
e sobre o problema do icone, nao consigo reproduzir no ubuntu gnome wayland, fedora 38 kde wayland e nem no arch linux wayland então não sei oq fazer, deve ser algum problema no flatpak

image

**Comment by Vilianexe** [comment]
Ss, imaginava, onde ele busca o ícone?

**Comment by Vilianexe** [comment]
É que preciso renomar o icone para exportar, talvez seja por isso?

**Comment by kassindornelles** [comment]
> É que preciso renomar o icone para exportar, talvez seja por isso?

não faço ideia, eu só posso informar que ele mudou de `lol-for-linux-installer.png` pra `lol-for-linux-installer.svg`

**Comment by Vilianexe** [comment]
estranho
onde ele detecta ou busca o ícone?, talvez eu consiga colocar um caminho diferente para quando estiver no flatpak

**Comment by kassindornelles** [comment]
pelo arquivo desktop que eu crio

 app.setDesktopFileName("com.kassindornelles.LolForLinuxInstaller")

local comum do arquivo svg:
/usr/share/lol-for-linux-installer/lol-for-linux-installer.svg

local do arquivo desktop que aponta o icone:
/usr/share/applications/com.kassindornelles.LolForLinuxInstaller.desktop

**Comment by Vilianexe** [comment]
descobri, o nome do .desktop, eu não consigo exportar o seu .desktop, com o nome que está agora, então eu sou obrigado a mudar para `com.kassindornelles.lol-for-linux-installer.desktop`, ou algo assim, então a gente precisa decidir, ou mudar o nome do .desktop que já está nesse repo, ou colocar um nome alternativo para quando ele estiver no flatpak

**Comment by Vilianexe** [comment]
se quiser eu consigo fazer, mas preciso saber oque vc prefere

**Comment by kassindornelles** [comment]
o nome do arquivo .desktop atual é `com.kassindornelles.LolForLinuxInstaller` n da pra usar esse nome?

**Comment by Vilianexe** [comment]
> o nome do arquivo .desktop atual é `com.kassindornelles.LolForLinuxInstaller` n da pra usar esse nome?

infelizmente não, nem eu entendo muito bem o porque, só que `Not exporting share/applications/com.kassindornelles.LolForLinuxInstaller.desktop, non-allowed export filename`

**Comment by kassindornelles** [comment]
mudei o nome pra com.kassindornelles.lolforlinuxinstaller, ta na main branch ja

**Comment by Vilianexe** [comment]
funcionou, brigado

**Comment by Vilianexe** [comment]
oque falta?

**Comment by Vilianexe** [comment]
deu uma limpada no yaml, de una olhada lá, ficou mais fácil de entender, tbm comecei a escrever o xml que dá as informações que vão mostrar na página do flathub, esse vc precisa revisar para garantir que eu não errei nada, já que vai ser a front page do app

**Comment by kassindornelles** [comment]
> oque falta?

falta eu testar e adaptar o codigo, não sei se vou conseguir essa semana

**Comment by Vilianexe** [comment]
> falta eu testar e adaptar o codigo, não sei se vou conseguir essa semana

tranquilo, eu termino o xml enquanto isso

**Comment by Vilianexe** [comment]
tive que refazer o repo do flathub pq apaguei oque não devia e não sabia arrumar, mandei um convite pra vc

**Comment by Vilianexe** [comment]
qualquer coisa eu transfiro ownership do repo pra vc

**Comment by Vilianexe** [comment]
vc fez uma release depois que alterou o nome dos arquivos?

**Comment by kassindornelles** [comment]
> vc fez uma release depois que alterou o nome dos arquivos?

Ainda não, mas o flatpak pode ter nome diferente, na verdade é até melhor

**Comment by Vilianexe** [comment]
> > vc fez uma release depois que alterou o nome dos arquivos?
> 
> Ainda não, mas o flatpak pode ter nome diferente, na verdade é até melhor

é que mudei a forma do flatpak puxar os seus arquivos de direto do repo, para as releases, ai deu conflito, se eu mudar agora quando a release mais atualizada lançar vou ter que arrumar de novo

**Comment by kassindornelles** [comment]
tem como trabalhar com a main branch por enquanto?

**Comment by Vilianexe** [comment]
> tem como trabalhar com a main branch por enquanto?

tem outras coisas pra resolver msm, então sem pressa

**Comment by kassindornelles** [comment]
mano ce vai ter que contribuir com codigo pq eu n faço a minima ideia de como o negocio funciona, e enviar o negocio pro flathub agora foi um erro pq eu nem sei oq fazer pra resolver metade dos problemas que isso tem

**Comment by Vilianexe** [comment]
era que eu ia tentar entender como o bot do flathub funciona ai criei o draft, mas o cara já veio dando 200 sugestões

**Comment by Vilianexe** [comment]
https://github.com/flathub/flathub/pull/4393#issuecomment-1668653258
ainda é um draft, eles não iriam adicionar

**Pull request closed without merging**
