### PR TITLE
Initial AppImage support

### PR DESCRIPTION
**Pull request by polkaulfield**
I managed to bundle the installer as an AppImage. I need further testing. Also changed the hardcoding of the wine paths to a variable.  The workaround for the AppImage is kinda hacky tho, I'll need to refactor the code but it works.

### CODE REVIEW

**Comment by polkaulfield** [comment]
Here's the AppImage, I need some testing with it but it works here: https://github.com/polkaulfield/lol-for-linux-installer/releases/download/appimage/lol-for-linux-installer-experimental.AppImage

**Comment by kassindornelles** [comment]
This is awesome, theres conflicts you need to solve before i can merge

**Comment by polkaulfield** [comment]
fixed conflict!

**Comment by kassindornelles** [comment]
do you think is ready to merge right now or theres anything else?

**Comment by polkaulfield** [comment]
It's a really dirty port, but works. We need a big rewrite. Also I have noticed that the script is downloading the icons from the repo when we have them already.

The ideal thing would be to make a python package with all the source. It's a lot easier that way. The appimage script moves some files to /usr/share/lolforlinux/ so the main script and the install script can see the other files, because they are not bundled in a package afaik. Thats why i added the `try:` `except:` code blocks to look for both paths.

Anyways it's the first AppImage i make so theres a ton of improvements that can be done. We can keep the repos separate until everyhting is well implemented. I just wanted a working appimage without messing too much with your code :)

**Comment by kassindornelles** [comment]
@polkaulfield not sure if you have discord but if you do add me there, my user is: kassin#2888

**Pull request merged**
